# 服务器端口
server:
  port: 8001


# 服务名
spring:
  application:
    name: edu-service

  # 环境设置 : dev、test、prod
  profiles:
    active: dev

  # 数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kaizen_school?serverTimezone=UTC
    username: root
    password: toor

  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper-locations: classpath:com/kaizen/edu/mapper/xml/*.xml