server:
  port: 8002

spring:
  application:
    name: service-oss

  profiles:
    active: dev

# 阿里云OSS
# 不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      keyid: LTAI4GAK8Ei4gy9MTqMHohyP
      keysecret: 4t859qr4Vy6HmkXDvjbGLUy7SiVbmc
      # bucket可以在控制台创建，也可以使用 java 代码创建
      bucketname: weizujie